[project]
name = "stock-markets-analytics-zoomcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rferper", email = "raquelfernandezperalta@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "gdown>=6.4.0",
    "lxml>=6.1.3",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "pandas-datareader>=0.11.1",
    "plotly>=7.1.0",
    "pyarrow>=25.0.1",
    "requests>=2.34.2",
    "yfinance>=1.7.0",
]

[project.scripts]
stock-markets-analytics-zoomcamp = "stock_markets_analytics_zoomcamp:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
